//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bobohairEntities : DbContext
    {
        public bobohairEntities()
            : base("name=bobohairEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        //public DbSet<T_Advice> T_Advice { get; set; }
        //public DbSet<T_Backflow> T_Backflow { get; set; }
        //public DbSet<T_Error> T_Error { get; set; }
        //public DbSet<T_Order> T_Order { get; set; }
        //public DbSet<T_Salon> T_Salon { get; set; }
        //public DbSet<T_SalonImageInfo> T_SalonImageInfo { get; set; }
        //public DbSet<T_SalonPackage> T_SalonPackage { get; set; }
        //public DbSet<T_Scanrec> T_Scanrec { get; set; }
        //public DbSet<T_Sms> T_Sms { get; set; }
        //public DbSet<T_Winning> T_Winning { get; set; }
        //public DbSet<T_Winningrec> T_Winningrec { get; set; }
        //public DbSet<Wx_Comment> Wx_Comment { get; set; }
        //public DbSet<To_Employee> To_Employee { get; set; }
        //public DbSet<T_SysInformation> T_SysInformation { get; set; }
        //public DbSet<Wx_Order> Wx_Order { get; set; }
        //public DbSet<Wx_BindHair> Wx_BindHair { get; set; }
        //public DbSet<T_CustomerManage> T_CustomerManage { get; set; }
        //public DbSet<Wx_Member> Wx_Member { get; set; }
        //public DbSet<T_SalinHairStylist> T_SalinHairStylist { get; set; }
        //public DbSet<T_HairOff> T_HairOff { get; set; }
        //public DbSet<T_Notice> T_Notice { get; set; }
        //public DbSet<T_SaleManager> T_SaleManager { get; set; }
    }
}
