//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ex_ad
    {
        public int ea_id { get; set; }
        public string ea_title { get; set; }
        public string ea_content { get; set; }
        public string ea_image { get; set; }
        public string ea_url { get; set; }
        public Nullable<int> ea_type { get; set; }
        public Nullable<System.DateTime> ea_date { get; set; }
        public Nullable<int> ea_status { get; set; }
    }
}
