//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ex_bookingorder
    {
        public int ebo_id { get; set; }
        public Nullable<System.Guid> ebo_uid { get; set; }
        public string ebo_cell { get; set; }
        public Nullable<System.Guid> ebo_eh_uid { get; set; }
        public Nullable<System.DateTime> ebo_date { get; set; }
        public string ebo_content { get; set; }
        public string ebo_about { get; set; }
        public string ebo_orderid { get; set; }
        public string ebo_payid { get; set; }
        public Nullable<int> ebo_paykind { get; set; }
        public Nullable<int> ebo_et_id { get; set; }
        public Nullable<double> ebo_price { get; set; }
        public Nullable<int> ebo_status { get; set; }
        public string ebo_out_refund_no { get; set; }
    }
}
