//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ex_comment
    {
        public int ec_id { get; set; }
        public Nullable<int> ec_ebo_id { get; set; }
        public string ec_content { get; set; }
        public Nullable<int> ec_score { get; set; }
        public Nullable<int> ec_status { get; set; }
    }
}
