//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ex_hair
    {
        public int eh_id { get; set; }
        public Nullable<System.Guid> eh_uid { get; set; }
        public string eh_name { get; set; }
        public string eh_logo { get; set; }
        public string eh_phone { get; set; }
        public string eh_cell { get; set; }
        public string eh_salonname { get; set; }
        public string eh_title { get; set; }
        public string eh_workingyears { get; set; }
        public string eh_skill { get; set; }
        public string eh_introduction { get; set; }
        public string eh_city { get; set; }
        public Nullable<System.DateTime> eh_applydate { get; set; }
        public Nullable<System.DateTime> eh_through { get; set; }
        public Nullable<int> eh_see { get; set; }
        public Nullable<int> eh_seeend { get; set; }
        public Nullable<int> eh_status { get; set; }
        public Nullable<int> eh_sort { get; set; }
    }
}
