//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ex_seerec
    {
        public int es_id { get; set; }
        public Nullable<System.Guid> es_uid { get; set; }
        public Nullable<System.Guid> es_eh_uid { get; set; }
        public Nullable<System.DateTime> es_date { get; set; }
        public Nullable<int> es_status { get; set; }
    }
}
