//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    //[DbConfigurationType(typeof(MySql.Data.Entity.MySqlEFConfiguration))]
    public partial class mysqkbobohairEntitesContainer : DbContext
    {
        public mysqkbobohairEntitesContainer()
            : base("name=mysqlbobohairEntites")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ex_ad> ex_ad { get; set; }
        public DbSet<ex_bookingorder> ex_bookingorder { get; set; }
        public DbSet<ex_comment> ex_comment { get; set; }
        public DbSet<ex_hair> ex_hair { get; set; }
        public DbSet<ex_seerec> ex_seerec { get; set; }
        public DbSet<ex_topic> ex_topic { get; set; }
        public DbSet<t_advice> t_advice { get; set; }
        public DbSet<t_backflow> t_backflow { get; set; }
        public DbSet<t_customermanage> t_customermanage { get; set; }
        public DbSet<t_error> t_error { get; set; }
        public DbSet<t_hairoff> t_hairoff { get; set; }
        public DbSet<t_notice> t_notice { get; set; }
        public DbSet<t_order> t_order { get; set; }
        public DbSet<t_salemanager> t_salemanager { get; set; }
        public DbSet<t_salinhairstylist> t_salinhairstylist { get; set; }
        public DbSet<t_salon> t_salon { get; set; }
        public DbSet<t_salonimageinfo> t_salonimageinfo { get; set; }
        public DbSet<t_salonpackage> t_salonpackage { get; set; }
        public DbSet<t_scanrec> t_scanrec { get; set; }
        public DbSet<t_sms> t_sms { get; set; }
        public DbSet<t_sysinformation> t_sysinformation { get; set; }
        public DbSet<t_winning> t_winning { get; set; }
        public DbSet<t_winningrec> t_winningrec { get; set; }
        public DbSet<to_activity> to_activity { get; set; }
        public DbSet<to_ad> to_ad { get; set; }
        public DbSet<to_address> to_address { get; set; }
        public DbSet<to_apns> to_apns { get; set; }
        public DbSet<to_apply> to_apply { get; set; }
        public DbSet<to_balanceofpayments> to_balanceofpayments { get; set; }
        public DbSet<to_bgerror> to_bgerror { get; set; }
        public DbSet<to_binding> to_binding { get; set; }
        public DbSet<wx_answers> wx_answers { get; set; }
        public DbSet<wx_article> wx_article { get; set; }
        public DbSet<wx_bindhair> wx_bindhair { get; set; }
        public DbSet<wx_comment> wx_comment { get; set; }
        public DbSet<wx_customerservice> wx_customerservice { get; set; }
        public DbSet<wx_impression> wx_impression { get; set; }
        public DbSet<wx_infromation> wx_infromation { get; set; }
        public DbSet<wx_location> wx_location { get; set; }
        public DbSet<wx_member> wx_member { get; set; }
        public DbSet<wx_order> wx_order { get; set; }
        public DbSet<wx_phonecall> wx_phonecall { get; set; }
        public DbSet<wx_post> wx_post { get; set; }
        public DbSet<wx_qrcode> wx_qrcode { get; set; }
        public DbSet<wx_questions> wx_questions { get; set; }
        public DbSet<wx_request> wx_request { get; set; }
        public DbSet<wx_searchcell> wx_searchcell { get; set; }
        public DbSet<wx_tip> wx_tip { get; set; }
        public DbSet<to_employee> to_employee { get; set; }
    }
}
