//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_advice
    {
        public int ad_id { get; set; }
        public string ad_content { get; set; }
        public Nullable<System.DateTime> ad_date { get; set; }
        public string ad_cell { get; set; }
        public Nullable<int> ad_kind { get; set; }
        public Nullable<int> ad_status { get; set; }
        public Nullable<System.Guid> ad_s_uid { get; set; }
    }
}
