//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_customermanage
    {
        public int cm_id { get; set; }
        public Nullable<System.Guid> cm_s_uid { get; set; }
        public string cm_s_nickname { get; set; }
        public Nullable<System.Guid> cm_h_uid { get; set; }
        public string cm_h_name { get; set; }
        public string cm_openid { get; set; }
        public string cm_nickname { get; set; }
        public string cm_remarks1 { get; set; }
        public string cm_remarks2 { get; set; }
        public string cm_remarks3 { get; set; }
        public string cm_remarks4 { get; set; }
        public string cm_remarks5 { get; set; }
        public Nullable<int> cm_status { get; set; }
    }
}
