//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_order
    {
        public int o_id { get; set; }
        public string o_orid { get; set; }
        public Nullable<System.Guid> o_s_uid { get; set; }
        public string o_name { get; set; }
        public Nullable<double> o_money { get; set; }
        public Nullable<System.DateTime> o_date { get; set; }
        public Nullable<System.DateTime> o_paydate { get; set; }
        public Nullable<int> o_status { get; set; }
    }
}
