//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_salinhairstylist
    {
        public System.Guid shs_h_uid { get; set; }
        public string shs_name { get; set; }
        public string shs_hairprice { get; set; }
        public string shs_exp { get; set; }
        public string shs_logo { get; set; }
        public Nullable<System.Guid> shs_s_uid { get; set; }
        public string shs_cell { get; set; }
        public Nullable<int> shs_sort { get; set; }
        public Nullable<int> shs_status { get; set; }
    }
}
