//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_salonimageinfo
    {
        public int si_id { get; set; }
        public Nullable<System.Guid> si_s_uid { get; set; }
        public string si_photo { get; set; }
        public Nullable<int> si_kind { get; set; }
        public Nullable<int> si_status { get; set; }
    }
}
