//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_salon
    {
        public System.Guid s_uid { get; set; }
        public string s_email { get; set; }
        public string s_cell { get; set; }
        public string s_pwd { get; set; }
        public string s_nickname { get; set; }
        public string s_logo { get; set; }
        public Nullable<System.DateTime> s_date { get; set; }
        public Nullable<int> s_kind { get; set; }
        public Nullable<int> s_status { get; set; }
        public string s_address { get; set; }
        public string s_linkname { get; set; }
        public string s_summary { get; set; }
        public string s_lon { get; set; }
        public string s_lat { get; set; }
        public string s_price { get; set; }
        public string s_wxname { get; set; }
        public Nullable<System.DateTime> s_opendate { get; set; }
        public string s_businessdate { get; set; }
        public string s_recommend { get; set; }
    }
}
