//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sysinformation
    {
        public int sy_id { get; set; }
        public string sy_title { get; set; }
        public string sy_content { get; set; }
        public Nullable<System.DateTime> sy_date { get; set; }
        public Nullable<int> sy_status { get; set; }
    }
}
