//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_winning
    {
        public int wig_id { get; set; }
        public Nullable<System.Guid> wig_s_uid { get; set; }
        public string wig_title { get; set; }
        public Nullable<System.DateTime> wig_date { get; set; }
        public string wig_image { get; set; }
        public Nullable<int> wig_pro { get; set; }
        public Nullable<int> wig_status { get; set; }
    }
}
