//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_winningrec
    {
        public int win_id { get; set; }
        public string win_content { get; set; }
        public Nullable<System.DateTime> win_date { get; set; }
        public string win_ip { get; set; }
        public string win_cell { get; set; }
        public Nullable<System.Guid> win_temuid { get; set; }
        public Nullable<System.Guid> win_s_uid { get; set; }
    }
}
