//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class to_address
    {
        public int od_id { get; set; }
        public Nullable<System.Guid> od_uid { get; set; }
        public string od_province { get; set; }
        public string od_city { get; set; }
        public string od_district { get; set; }
        public string od_detailed { get; set; }
        public Nullable<int> od_default { get; set; }
        public string od_lon { get; set; }
        public string od_lat { get; set; }
    }
}
