//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class to_apns
    {
        public int ao_id { get; set; }
        public string ao_cell { get; set; }
        public string ao_tokenid { get; set; }
        public Nullable<System.Guid> ao_cid { get; set; }
        public Nullable<System.DateTime> ao_date { get; set; }
        public Nullable<int> ao_device { get; set; }
        public Nullable<int> ao_apptype { get; set; }
    }
}
