//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class to_apply
    {
        public int ap_id { get; set; }
        public Nullable<System.Guid> ap_uid { get; set; }
        public string ap_cell { get; set; }
        public string ap_name { get; set; }
        public string ap_idcard { get; set; }
        public string ap_salonname { get; set; }
        public string ap_salonaddress { get; set; }
        public string ap_gps { get; set; }
        public Nullable<int> ap_status { get; set; }
        public Nullable<System.DateTime> ap_date { get; set; }
        public Nullable<System.DateTime> ap_adate { get; set; }
        public Nullable<int> ap_sex { get; set; }
        public Nullable<int> ap_open { get; set; }
    }
}
