//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class to_ad
    {
        public int oa_id { get; set; }
        public string oa_image { get; set; }
        public string oa_url { get; set; }
        public Nullable<System.DateTime> oa_date { get; set; }
        public Nullable<int> oa_status { get; set; }
        public string oa_title { get; set; }
        public string oa_content { get; set; }
        public Nullable<int> oa_sort { get; set; }
    }
}
