//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class to_balanceofpayments
    {
        public int bp_id { get; set; }
        public Nullable<System.Guid> bp_oe_uid { get; set; }
        public Nullable<int> bp_type { get; set; }
        public Nullable<int> bp_source { get; set; }
        public string bp_title { get; set; }
        public Nullable<double> bp_money { get; set; }
        public string bp_payid { get; set; }
        public Nullable<int> bp_kind { get; set; }
        public Nullable<System.DateTime> bp_date { get; set; }
        public Nullable<int> bp_status { get; set; }
        public Nullable<int> bp_orderid { get; set; }
        public Nullable<int> bp_table { get; set; }
        public Nullable<int> bp_oreid { get; set; }
    }
}
