//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class to_binding
    {
        public int bd_id { get; set; }
        public Nullable<System.Guid> bd_oe_uid { get; set; }
        public string bd_account { get; set; }
        public Nullable<int> bd_kind { get; set; }
        public Nullable<System.DateTime> bd_date { get; set; }
        public Nullable<int> bd_status { get; set; }
        public string bd_name { get; set; }
    }
}
