//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class to_employee
    {
        public System.Guid oe_uid { get; set; }
        public string oe_name { get; set; }
        public Nullable<int> oe_sex { get; set; }
        public string oe_logo { get; set; }
        public string oe_lon { get; set; }
        public string oe_lat { get; set; }
        public string oe_introduce { get; set; }
        public Nullable<int> oe_sort { get; set; }
        public Nullable<int> oe_workstatus { get; set; }
        public string oe_cell { get; set; }
        public Nullable<System.Guid> oe_cuid { get; set; }
        public Nullable<int> oe_status { get; set; }
        public Nullable<int> oe_sa { get; set; }
        public Nullable<double> oe_quota { get; set; }
        public Nullable<int> oe_grade { get; set; }
        public Nullable<System.Guid> oe_b_uid { get; set; }
        public Nullable<System.Guid> oe_s_uid { get; set; }
        public string oe_idcard { get; set; }
        public Nullable<double> oe_income { get; set; }
        public Nullable<double> oe_price { get; set; }
        public string oe_worktime { get; set; }
        public string oe_restday { get; set; }
    }
}
