//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_answers
    {
        public int wa_id { get; set; }
        public Nullable<System.Guid> wa_h_uid { get; set; }
        public string wa_openid { get; set; }
        public Nullable<System.DateTime> wa_date { get; set; }
        public string wa_content { get; set; }
        public string wa_image { get; set; }
        public Nullable<int> wa_wq_id { get; set; }
        public Nullable<int> wa_replyid { get; set; }
        public Nullable<int> wa_status { get; set; }
        public string wa_attribute { get; set; }
        public Nullable<int> wa_hot { get; set; }
    }
}
