//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_infromation
    {
        public int wim_id { get; set; }
        public string wim_title { get; set; }
        public string wim_content { get; set; }
        public string wim_image { get; set; }
        public Nullable<System.DateTime> wim_date { get; set; }
        public string wim_url { get; set; }
        public Nullable<int> wim_status { get; set; }
        public Nullable<int> wim_push_status { get; set; }
    }
}
