//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_location
    {
        public int wl_id { get; set; }
        public string wl_lng { get; set; }
        public string wl_lat { get; set; }
        public string wl_openid { get; set; }
        public Nullable<System.DateTime> wl_date { get; set; }
    }
}
