//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_member
    {
        public string wm_openid { get; set; }
        public string wm_cell { get; set; }
        public Nullable<int> wm_subscribe { get; set; }
        public string wm_nickname { get; set; }
        public Nullable<int> wm_sex { get; set; }
        public string wm_city { get; set; }
        public string wm_country { get; set; }
        public string wm_province { get; set; }
        public string wm_language { get; set; }
        public string wm_headimgurl { get; set; }
        public string wm_subscribe_time { get; set; }
        public string wm_unionid { get; set; }
        public Nullable<int> wm_type { get; set; }
        public string wm_pwd { get; set; }
    }
}
