//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_order
    {
        public int wo_id { get; set; }
        public string wo_openid { get; set; }
        public Nullable<System.Guid> wo_h_uid { get; set; }
        public Nullable<System.DateTime> wo_bookingdate { get; set; }
        public Nullable<System.DateTime> wo_date { get; set; }
        public string wo_cell { get; set; }
        public string wo_remarks { get; set; }
        public string wo_image { get; set; }
        public Nullable<int> wo_status { get; set; }
        public Nullable<int> wo_type { get; set; }
        public Nullable<int> wo_source { get; set; }
        public string wo_adress { get; set; }
        public string wo_orderid { get; set; }
        public string wo_payid { get; set; }
        public Nullable<int> wo_paykind { get; set; }
        public Nullable<int> wo_orderstatus { get; set; }
        public Nullable<double> wo_price { get; set; }
        public string wo_out_refund_no { get; set; }
        public Nullable<System.Guid> wo_s_uid { get; set; }
    }
}
