//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_phonecall
    {
        public int wpc_id { get; set; }
        public Nullable<System.Guid> wpc_openid { get; set; }
        public Nullable<System.Guid> wpc_h_uid { get; set; }
        public string wpc_cell { get; set; }
        public Nullable<System.DateTime> wpc_date { get; set; }
    }
}
