//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_questions
    {
        public int wq_id { get; set; }
        public string wq_title { get; set; }
        public string wq_openid { get; set; }
        public Nullable<System.DateTime> wq_date { get; set; }
        public string wq_content { get; set; }
        public string wq_image1 { get; set; }
        public string wq_image2 { get; set; }
        public Nullable<int> wq_type { get; set; }
        public Nullable<int> wq_status { get; set; }
    }
}
