//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_qrcode
    {
        public int qr_id { get; set; }
        public string qr_ticket { get; set; }
        public Nullable<System.Guid> qr_h_uid { get; set; }
        public Nullable<System.DateTime> qr_date { get; set; }
        public Nullable<int> qr_num { get; set; }
        public Nullable<int> qr_type { get; set; }
        public Nullable<int> qr_code { get; set; }
    }
}
