//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boboframework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_tip
    {
        public int wt_id { get; set; }
        public string wt_openid { get; set; }
        public Nullable<System.Guid> wt_h_uid { get; set; }
        public Nullable<double> wt_price { get; set; }
        public string wt_orderid { get; set; }
        public string wt_payid { get; set; }
        public Nullable<int> wt_paykind { get; set; }
        public Nullable<System.DateTime> wt_date { get; set; }
        public Nullable<int> wt_status { get; set; }
    }
}
